theme: jekyll-theme-minimal
title: SanBingYouYong
description: BSc Computer Science graduate with First-class honours from the University of Edinburgh. Starting MSc Advanced Computing at Imperial College London. 
