[project]
name = "sanbingyouyong.github.io"
version = "0.1.0"
description = "Personal web page with Material for MkDocs"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mkdocs-material>=9.6.21",
]
